package wasvy:ecs;

interface guest {
	// guest provides the system resource implementation
    resource system {
        run: func(input: string) -> string;
    }

	// and a setup function
	setup: func();
}

interface app {
	use guest.{system};

    resource app {
        constructor();
        add-system: func(system: system);
    }
}

world host {
    export app;
    import guest;
}
