package wasvy:ecs;

interface sys {
    resource system {
        run: func(input: string) -> string;
    }
}

interface app {
	use sys.{system};

    resource app {
        constructor();
        add-system: func(sys: system);
    }
}

world host {
    export app;
    import sys;
}

world guest {
    // guest provides the system resource implementation
    export sys;

	// and a setup function
	export setup: func();
}
